// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/proto/mensagem.proto

package br.ufs.dcomp.ChatRabbitMQ;

public final class Mensagem {
  private Mensagem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MensagemUsuarioOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CorpoMensagem.MensagemUsuario)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string hora = 1;</code>
     * @return The hora.
     */
    java.lang.String getHora();
    /**
     * <code>string hora = 1;</code>
     * @return The bytes for hora.
     */
    com.google.protobuf.ByteString
        getHoraBytes();

    /**
     * <code>string nome = 2;</code>
     * @return The nome.
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 2;</code>
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>string grupo = 3;</code>
     * @return The grupo.
     */
    java.lang.String getGrupo();
    /**
     * <code>string grupo = 3;</code>
     * @return The bytes for grupo.
     */
    com.google.protobuf.ByteString
        getGrupoBytes();

    /**
     * <code>string mensagem = 4;</code>
     * @return The mensagem.
     */
    java.lang.String getMensagem();
    /**
     * <code>string mensagem = 4;</code>
     * @return The bytes for mensagem.
     */
    com.google.protobuf.ByteString
        getMensagemBytes();
  }
  /**
   * Protobuf type {@code CorpoMensagem.MensagemUsuario}
   */
  public static final class MensagemUsuario extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CorpoMensagem.MensagemUsuario)
      MensagemUsuarioOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MensagemUsuario.newBuilder() to construct.
    private MensagemUsuario(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MensagemUsuario() {
      hora_ = "";
      nome_ = "";
      grupo_ = "";
      mensagem_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MensagemUsuario();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MensagemUsuario(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hora_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nome_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              grupo_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              mensagem_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufs.dcomp.ChatRabbitMQ.Mensagem.internal_static_CorpoMensagem_MensagemUsuario_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufs.dcomp.ChatRabbitMQ.Mensagem.internal_static_CorpoMensagem_MensagemUsuario_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario.class, br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario.Builder.class);
    }

    public static final int HORA_FIELD_NUMBER = 1;
    private volatile java.lang.Object hora_;
    /**
     * <code>string hora = 1;</code>
     * @return The hora.
     */
    @java.lang.Override
    public java.lang.String getHora() {
      java.lang.Object ref = hora_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hora_ = s;
        return s;
      }
    }
    /**
     * <code>string hora = 1;</code>
     * @return The bytes for hora.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHoraBytes() {
      java.lang.Object ref = hora_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hora_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOME_FIELD_NUMBER = 2;
    private volatile java.lang.Object nome_;
    /**
     * <code>string nome = 2;</code>
     * @return The nome.
     */
    @java.lang.Override
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 2;</code>
     * @return The bytes for nome.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GRUPO_FIELD_NUMBER = 3;
    private volatile java.lang.Object grupo_;
    /**
     * <code>string grupo = 3;</code>
     * @return The grupo.
     */
    @java.lang.Override
    public java.lang.String getGrupo() {
      java.lang.Object ref = grupo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        grupo_ = s;
        return s;
      }
    }
    /**
     * <code>string grupo = 3;</code>
     * @return The bytes for grupo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGrupoBytes() {
      java.lang.Object ref = grupo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        grupo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MENSAGEM_FIELD_NUMBER = 4;
    private volatile java.lang.Object mensagem_;
    /**
     * <code>string mensagem = 4;</code>
     * @return The mensagem.
     */
    @java.lang.Override
    public java.lang.String getMensagem() {
      java.lang.Object ref = mensagem_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mensagem_ = s;
        return s;
      }
    }
    /**
     * <code>string mensagem = 4;</code>
     * @return The bytes for mensagem.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMensagemBytes() {
      java.lang.Object ref = mensagem_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mensagem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHoraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hora_);
      }
      if (!getNomeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nome_);
      }
      if (!getGrupoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, grupo_);
      }
      if (!getMensagemBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mensagem_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHoraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hora_);
      }
      if (!getNomeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nome_);
      }
      if (!getGrupoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, grupo_);
      }
      if (!getMensagemBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mensagem_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario)) {
        return super.equals(obj);
      }
      br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario other = (br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario) obj;

      if (!getHora()
          .equals(other.getHora())) return false;
      if (!getNome()
          .equals(other.getNome())) return false;
      if (!getGrupo()
          .equals(other.getGrupo())) return false;
      if (!getMensagem()
          .equals(other.getMensagem())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HORA_FIELD_NUMBER;
      hash = (53 * hash) + getHora().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + GRUPO_FIELD_NUMBER;
      hash = (53 * hash) + getGrupo().hashCode();
      hash = (37 * hash) + MENSAGEM_FIELD_NUMBER;
      hash = (53 * hash) + getMensagem().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CorpoMensagem.MensagemUsuario}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CorpoMensagem.MensagemUsuario)
        br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuarioOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ChatRabbitMQ.Mensagem.internal_static_CorpoMensagem_MensagemUsuario_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ChatRabbitMQ.Mensagem.internal_static_CorpoMensagem_MensagemUsuario_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario.class, br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario.Builder.class);
      }

      // Construct using br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hora_ = "";

        nome_ = "";

        grupo_ = "";

        mensagem_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufs.dcomp.ChatRabbitMQ.Mensagem.internal_static_CorpoMensagem_MensagemUsuario_descriptor;
      }

      @java.lang.Override
      public br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario getDefaultInstanceForType() {
        return br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario.getDefaultInstance();
      }

      @java.lang.Override
      public br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario build() {
        br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario buildPartial() {
        br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario result = new br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario(this);
        result.hora_ = hora_;
        result.nome_ = nome_;
        result.grupo_ = grupo_;
        result.mensagem_ = mensagem_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario) {
          return mergeFrom((br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario other) {
        if (other == br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario.getDefaultInstance()) return this;
        if (!other.getHora().isEmpty()) {
          hora_ = other.hora_;
          onChanged();
        }
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        if (!other.getGrupo().isEmpty()) {
          grupo_ = other.grupo_;
          onChanged();
        }
        if (!other.getMensagem().isEmpty()) {
          mensagem_ = other.mensagem_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object hora_ = "";
      /**
       * <code>string hora = 1;</code>
       * @return The hora.
       */
      public java.lang.String getHora() {
        java.lang.Object ref = hora_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hora_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hora = 1;</code>
       * @return The bytes for hora.
       */
      public com.google.protobuf.ByteString
          getHoraBytes() {
        java.lang.Object ref = hora_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hora_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hora = 1;</code>
       * @param value The hora to set.
       * @return This builder for chaining.
       */
      public Builder setHora(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hora_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hora = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHora() {
        
        hora_ = getDefaultInstance().getHora();
        onChanged();
        return this;
      }
      /**
       * <code>string hora = 1;</code>
       * @param value The bytes for hora to set.
       * @return This builder for chaining.
       */
      public Builder setHoraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hora_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 2;</code>
       * @return The nome.
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 2;</code>
       * @return The bytes for nome.
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 2;</code>
       * @param value The nome to set.
       * @return This builder for chaining.
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 2;</code>
       * @param value The bytes for nome to set.
       * @return This builder for chaining.
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object grupo_ = "";
      /**
       * <code>string grupo = 3;</code>
       * @return The grupo.
       */
      public java.lang.String getGrupo() {
        java.lang.Object ref = grupo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          grupo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string grupo = 3;</code>
       * @return The bytes for grupo.
       */
      public com.google.protobuf.ByteString
          getGrupoBytes() {
        java.lang.Object ref = grupo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          grupo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string grupo = 3;</code>
       * @param value The grupo to set.
       * @return This builder for chaining.
       */
      public Builder setGrupo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        grupo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string grupo = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGrupo() {
        
        grupo_ = getDefaultInstance().getGrupo();
        onChanged();
        return this;
      }
      /**
       * <code>string grupo = 3;</code>
       * @param value The bytes for grupo to set.
       * @return This builder for chaining.
       */
      public Builder setGrupoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        grupo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mensagem_ = "";
      /**
       * <code>string mensagem = 4;</code>
       * @return The mensagem.
       */
      public java.lang.String getMensagem() {
        java.lang.Object ref = mensagem_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mensagem_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mensagem = 4;</code>
       * @return The bytes for mensagem.
       */
      public com.google.protobuf.ByteString
          getMensagemBytes() {
        java.lang.Object ref = mensagem_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mensagem_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mensagem = 4;</code>
       * @param value The mensagem to set.
       * @return This builder for chaining.
       */
      public Builder setMensagem(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mensagem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mensagem = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMensagem() {
        
        mensagem_ = getDefaultInstance().getMensagem();
        onChanged();
        return this;
      }
      /**
       * <code>string mensagem = 4;</code>
       * @param value The bytes for mensagem to set.
       * @return This builder for chaining.
       */
      public Builder setMensagemBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mensagem_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CorpoMensagem.MensagemUsuario)
    }

    // @@protoc_insertion_point(class_scope:CorpoMensagem.MensagemUsuario)
    private static final br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario();
    }

    public static br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MensagemUsuario>
        PARSER = new com.google.protobuf.AbstractParser<MensagemUsuario>() {
      @java.lang.Override
      public MensagemUsuario parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MensagemUsuario(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MensagemUsuario> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MensagemUsuario> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.ufs.dcomp.ChatRabbitMQ.Mensagem.MensagemUsuario getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CorpoMensagem_MensagemUsuario_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CorpoMensagem_MensagemUsuario_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/java/proto/mensagem.proto\022\rCo" +
      "rpoMensagem\"N\n\017MensagemUsuario\022\014\n\004hora\030\001" +
      " \001(\t\022\014\n\004nome\030\002 \001(\t\022\r\n\005grupo\030\003 \001(\t\022\020\n\010men" +
      "sagem\030\004 \001(\tB%\n\031br.ufs.dcomp.ChatRabbitMQ" +
      "B\010Mensagemb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CorpoMensagem_MensagemUsuario_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CorpoMensagem_MensagemUsuario_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CorpoMensagem_MensagemUsuario_descriptor,
        new java.lang.String[] { "Hora", "Nome", "Grupo", "Mensagem", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
